// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	profile.proto

It has these top-level messages:
	Profile
	Profiles
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Profile struct {
	Id         uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FirebaseId string `protobuf:"bytes,2,opt,name=firebaseId" json:"firebaseId,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Alias      string `protobuf:"bytes,4,opt,name=alias" json:"alias,omitempty"`
	Username   string `protobuf:"bytes,5,opt,name=username" json:"username,omitempty"`
	Lastname   string `protobuf:"bytes,6,opt,name=lastname" json:"lastname,omitempty"`
	Email      string `protobuf:"bytes,7,opt,name=email" json:"email,omitempty"`
	Birthday   string `protobuf:"bytes,8,opt,name=birthday" json:"birthday,omitempty"`
	Status     string `protobuf:"bytes,9,opt,name=status" json:"status,omitempty"`
	Role       string `protobuf:"bytes,10,opt,name=role" json:"role,omitempty"`
}

func (m *Profile) Reset()                    { *m = Profile{} }
func (m *Profile) String() string            { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()               {}
func (*Profile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Profile) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Profile) GetFirebaseId() string {
	if m != nil {
		return m.FirebaseId
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Profile) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Profile) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Profile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Profile) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *Profile) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Profile) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type Profiles struct {
	Offset   int32      `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Limit    int32      `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Page     int32      `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	Count    int32      `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`
	Profiles []*Profile `protobuf:"bytes,5,rep,name=profiles" json:"profiles,omitempty"`
}

func (m *Profiles) Reset()                    { *m = Profiles{} }
func (m *Profiles) String() string            { return proto.CompactTextString(m) }
func (*Profiles) ProtoMessage()               {}
func (*Profiles) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Profiles) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Profiles) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Profiles) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Profiles) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Profiles) GetProfiles() []*Profile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func init() {
	proto.RegisterType((*Profile)(nil), "grpc.Profile")
	proto.RegisterType((*Profiles)(nil), "grpc.Profiles")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for ProfileService service

type ProfileServiceClient interface {
	Create(ctx context.Context, in *Profile, opts ...grpc1.CallOption) (*Profile, error)
	Update(ctx context.Context, in *Profile, opts ...grpc1.CallOption) (*Profile, error)
	Find(ctx context.Context, in *Profile, opts ...grpc1.CallOption) (*Profiles, error)
	FindById(ctx context.Context, in *Profile, opts ...grpc1.CallOption) (*Profile, error)
	DeleteById(ctx context.Context, in *Profile, opts ...grpc1.CallOption) (*Profile, error)
}

type profileServiceClient struct {
	cc *grpc1.ClientConn
}

func NewProfileServiceClient(cc *grpc1.ClientConn) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) Create(ctx context.Context, in *Profile, opts ...grpc1.CallOption) (*Profile, error) {
	out := new(Profile)
	err := grpc1.Invoke(ctx, "/grpc.ProfileService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Update(ctx context.Context, in *Profile, opts ...grpc1.CallOption) (*Profile, error) {
	out := new(Profile)
	err := grpc1.Invoke(ctx, "/grpc.ProfileService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Find(ctx context.Context, in *Profile, opts ...grpc1.CallOption) (*Profiles, error) {
	out := new(Profiles)
	err := grpc1.Invoke(ctx, "/grpc.ProfileService/Find", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) FindById(ctx context.Context, in *Profile, opts ...grpc1.CallOption) (*Profile, error) {
	out := new(Profile)
	err := grpc1.Invoke(ctx, "/grpc.ProfileService/FindById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) DeleteById(ctx context.Context, in *Profile, opts ...grpc1.CallOption) (*Profile, error) {
	out := new(Profile)
	err := grpc1.Invoke(ctx, "/grpc.ProfileService/DeleteById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProfileService service

type ProfileServiceServer interface {
	Create(context.Context, *Profile) (*Profile, error)
	Update(context.Context, *Profile) (*Profile, error)
	Find(context.Context, *Profile) (*Profiles, error)
	FindById(context.Context, *Profile) (*Profile, error)
	DeleteById(context.Context, *Profile) (*Profile, error)
}

func RegisterProfileServiceServer(s *grpc1.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Profile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Create(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ProfileService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Create(ctx, req.(*Profile))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Profile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Update(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ProfileService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Update(ctx, req.(*Profile))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Profile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Find(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ProfileService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Find(ctx, req.(*Profile))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Profile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).FindById(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ProfileService/FindById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).FindById(ctx, req.(*Profile))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_DeleteById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Profile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).DeleteById(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ProfileService/DeleteById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).DeleteById(ctx, req.(*Profile))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProfileService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProfileService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProfileService_Update_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _ProfileService_Find_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _ProfileService_FindById_Handler,
		},
		{
			MethodName: "DeleteById",
			Handler:    _ProfileService_DeleteById_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "profile.proto",
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4e, 0x32, 0x31,
	0x10, 0xc7, 0x59, 0xd8, 0x2e, 0xcb, 0x7c, 0x81, 0x43, 0xf3, 0xc5, 0x34, 0x1c, 0x0c, 0xd9, 0x8b,
	0xab, 0x31, 0x1c, 0xf0, 0x0d, 0xd4, 0x98, 0x70, 0x33, 0x35, 0x3e, 0x40, 0xa1, 0xb3, 0xd8, 0xa4,
	0xb0, 0x9b, 0xb6, 0x98, 0xf0, 0x10, 0x3e, 0xa7, 0xcf, 0xe0, 0xcd, 0xb4, 0x5d, 0x88, 0xeb, 0x45,
	0x6e, 0xf3, 0x9b, 0xff, 0x7f, 0xa6, 0x33, 0x93, 0xc2, 0xb8, 0x31, 0x75, 0xa5, 0x34, 0xce, 0x1b,
	0x53, 0xbb, 0x9a, 0xa6, 0x1b, 0xd3, 0xac, 0x8b, 0xaf, 0x04, 0x86, 0xcf, 0x31, 0x4f, 0x27, 0xd0,
	0x57, 0x92, 0x25, 0xb3, 0xa4, 0x1c, 0xf3, 0xbe, 0x92, 0xf4, 0x12, 0xa0, 0x52, 0x06, 0x57, 0xc2,
	0xe2, 0x52, 0xb2, 0xfe, 0x2c, 0x29, 0x47, 0xfc, 0x47, 0x86, 0x52, 0x48, 0x77, 0x62, 0x8b, 0x6c,
	0x10, 0x94, 0x10, 0xd3, 0xff, 0x40, 0x84, 0x56, 0xc2, 0xb2, 0x34, 0x24, 0x23, 0xd0, 0x29, 0xe4,
	0x7b, 0x8b, 0x26, 0xb8, 0x49, 0x10, 0x4e, 0xec, 0x35, 0x2d, 0xac, 0x0b, 0x5a, 0x16, 0xb5, 0x23,
	0xfb, 0x6e, 0xb8, 0x15, 0x4a, 0xb3, 0x61, 0xec, 0x16, 0xc0, 0x57, 0xac, 0x94, 0x71, 0x6f, 0x52,
	0x1c, 0x58, 0x1e, 0x2b, 0x8e, 0x4c, 0x2f, 0x20, 0xb3, 0x4e, 0xb8, 0xbd, 0x65, 0xa3, 0xa0, 0xb4,
	0xe4, 0x67, 0x35, 0xb5, 0x46, 0x06, 0x71, 0x56, 0x1f, 0x17, 0x1f, 0x09, 0xe4, 0xed, 0xee, 0xd6,
	0x17, 0xd6, 0x55, 0x65, 0xd1, 0x85, 0x03, 0x10, 0xde, 0x92, 0x1f, 0x41, 0xab, 0xad, 0x72, 0x61,
	0x7f, 0xc2, 0x23, 0xf8, 0x76, 0x8d, 0xd8, 0xc4, 0xd5, 0x09, 0x0f, 0xb1, 0x77, 0xae, 0xeb, 0xfd,
	0xce, 0x85, 0xd5, 0x09, 0x8f, 0x40, 0xaf, 0x21, 0x6f, 0xef, 0x6e, 0x19, 0x99, 0x0d, 0xca, 0x7f,
	0x8b, 0xf1, 0xdc, 0x5f, 0x7e, 0xde, 0xbe, 0xcc, 0x4f, 0xf2, 0xe2, 0x33, 0x81, 0x49, 0x9b, 0x7d,
	0x41, 0xf3, 0xae, 0xd6, 0x48, 0x4b, 0xc8, 0x1e, 0x0c, 0x0a, 0x87, 0xb4, 0x5b, 0x35, 0xed, 0x62,
	0xd1, 0xf3, 0xce, 0xd7, 0x46, 0x9e, 0xe3, 0xbc, 0x82, 0xf4, 0x49, 0xed, 0xe4, 0x6f, 0xdf, 0xa4,
	0x83, 0xb6, 0xe8, 0xd1, 0x1b, 0xc8, 0xbd, 0xf1, 0xfe, 0xb0, 0x94, 0x7f, 0x36, 0xbd, 0x05, 0x78,
	0x44, 0x8d, 0x0e, 0xcf, 0x71, 0xaf, 0xb2, 0xf0, 0x05, 0xef, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x1d, 0xbf, 0x71, 0x33, 0x93, 0x02, 0x00, 0x00,
}
